In [1]:
import numpy as np
d = np.array([[1,2,10],[12,3,2]])

In [2]:
d

array([[ 1,  2, 10],
       [12,  3,  2]])

In [3]:
for i in d:
    print(i)

[ 1  2 10]
[12  3  2]


In [4]:
np.array([1,2,3])*np.array([1,2,4])

array([ 1,  4, 12])

In [5]:
def inputs(data):
    return np.array(data)

In [6]:
inputs(d)

array([[ 1,  2, 10],
       [12,  3,  2]])

In [7]:
hidden_layers = []
def hidden_layer(number_of_hidden_layer,number_of_neurons):
    for i in range(number_of_hidden_layer):
#         hidden_layers.append(np.zeros(inputs(,number_of_neurons[i]))
        hidden_layers.append(np.zeros(number_of_neurons[i]))
    return hidden_layers
hidden_layers = []

In [8]:
# hidden_layer(2,[3,2])

In [9]:
# hidden_layers

In [10]:
def output(shape):
    return np.zeros(shape)

In [11]:
# output(10)

In [12]:
weight = []
def graph(data,number_of_hidden_layer,number_of_neurons,shape):
    lists = np.array([inputs(data),hidden_layer(number_of_hidden_layer,number_of_neurons),output(shape)])
    weight.append(np.zeros([lists[0].shape[0],lists[1][0].shape[0]]))
    for j in range(len(lists[1])-1):
#         print(lists[1][j].shape[0],lists[1][j+1].shape[0])
        weight.append(np.zeros([lists[1][j+1].shape[0],lists[1][j].shape[0]]))
    weight.append(np.zeros([lists[-1].shape[0],lists[1][-1].shape[0]]))
    print(weight)
    hidden_layers = []
    return lists,weight

In [13]:
# print(graph([1,2,4],2,[3,2],10))

In [14]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [15]:
lists,weight = graph([1,2,4],2,[3,2],10)

[array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]]), array([[0., 0., 0.],
       [0., 0., 0.]]), array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])]


In [16]:


def forward_propagation():
    z= []
    index = 0
    for i in weight[0]:
#         print(i,lists[0])
        z.append(np.array(i*lists[0]))
#     print(z)
    for i in range(len(lists[1][0])):
#         print(i)
        lists[1][0][i] = sigmoid(sum(z[i]))
#     print(lists)
    for k in range(1,len(lists[1])):
        z = []
        for hidden_layer in weight[k]:
            
#             print(hidden_layer,lists[1][index])
            z.append(np.array(hidden_layer*lists[1][index]))
#         print(z)
        print(z)
        for i in range(len(lists[1][k])):
#             print(len(lists[1][k]))
#             print(i)
#             print(lists[1][index])
#             print(z[1])
#             print(sum(z[i]))
#             print(lists[1][k][i])
#             print(len(lists[1][k]))
#             print(lists[1][k][0],'///////')
#             print(sigmoid(sum(z[i])))
            lists[1][k][i] = sigmoid(sum(z[i]))
        index = index + 1
    z=[]
    for last in weight[-1]:
        z.append(np.array(last*lists[1][-1]))
#     print(z)
    for i in range(len(lists[-1])):
#         print(z[i])
        lists[-1][i] = sigmoid(sum(z[i]))
print(lists)
    
#     lists[1][0] = 
    
#     lists = graph(data,number_of_hidden_layer,number_of_neurons,shape)
    
    
#     print(lists[0].shape[0],lists[1][0].shape[0])

[array([1, 2, 4]) list([array([0., 0., 0.]), array([0., 0.])])
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]


In [17]:
forward_propagation()

[array([0., 0., 0.]), array([0., 0., 0.])]


In [18]:
lists

array([array([1, 2, 4]),
       list([array([0.5, 0.5, 0.5]), array([0.5, 0.5])]),
       array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])],
      dtype=object)

In [126]:
d=[1,3,4]

In [9]:
weight

[array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]), array([[0., 0., 0.],
        [0., 0., 0.]]), array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])]

In [50]:
lists[1][0]

array([0.5, 0.5, 0.5])

In [22]:
lists

array([array([1, 2, 4]),
       list([array([0.5, 0.5, 0.5]), array([0.5, 0.5])]),
       array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])], dtype=object)

In [23]:
lists[-1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
print(len(lists[-1]))

10


In [28]:
d = np.array([1,2,3]); l = np.array([1,3,4])

In [29]:
k = d*l

In [30]:
#cost function
def cost_function():
    return (1/2)*()

array([ 1,  6, 12])

In [ ]:
def backpropagation():
    